### ISSUE TITLE
Espeak does not work on Debian

### ISSUE THREAD

**Issue by EvanMisshula** [smythp/eloud#17]
Linux euler 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

$ which espeak
/usr/bin/espeak

espeak works from the command line but eloud does not work.

**Comment by smythp** [comment]
Can you confirm that the path variable eloud-espeak-path is set to "/usr/bin/espeak"?

**Comment by smythp** [comment]
Also let me know if you get messages when you do M-x eloud-mode
